import { Router } from 'express';
import authRoutes from './features/auth/routes/auth.routes';
import userRoutes from './features/users/routes/user.routes';
import roleRoutes from './features/roles/routes/role.routes';
import permissionRoutes from './features/permissions/routes/permission.routes';
import studentRoutes from './features/students/routes/student.routes';
import driverRoutes from './features/drivers/routes/driver.routes';
import busRoutes from './features/buses/routes/bus.routes';
import routeRoutes from './features/routes/routes/route.routes';
import busStopRoutes from './features/busStops/routes/busStop.routes';
import destinationRoutes from './features/destinations/routes/destination.routes';
import tripRoutes from './features/trips/routes/trip.routes';
import attendanceRoutes from './features/attendance/routes/attendance.routes';
import subscriptionRoutes from './features/subscriptions/routes/subscription.routes';
import maintenanceRoutes from './features/maintenance/routes/maintenance.routes';
import maintenanceTypeRoutes from './features/maintenance/routes/maintenanceType.routes';
import fuelRoutes from './features/fuel/routes/fuel.routes';
import notificationRoutes from './features/notifications/routes/notification.routes';
import reportRoutes from './features/reports/routes/report.routes';
import dashboardRoutes from './features/dashboard/routes/dashboard.routes';
import settingRoutes from './features/settings/routes/setting.routes';
import logRoutes from './features/logs/routes/log.routes';
import uploadRoutes from './features/uploads/routes/upload.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/students', studentRoutes);
router.use('/drivers', driverRoutes);
router.use('/buses', busRoutes);
router.use('/routes', routeRoutes);
router.use('/bus-stops', busStopRoutes);
router.use('/destinations', destinationRoutes);
router.use('/trips', tripRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/maintenance/types', maintenanceTypeRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/fuel', fuelRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingRoutes);
router.use('/logs', logRoutes);
router.use('/uploads', uploadRoutes);

export default router;
